

# Project Documentation

Created by: Jordan Auerbach, Shivani Joshi, Stephen Sherwood, Tyler Treat

### Goals
As living beings, we experience the tension between having to eat to survive, yet every meal has the potential to make us ill, or in rare cases, even kill us. It’s estimated that foodborne illnesses affect 48 million people annually in the United States. The Center for Disease Control and Prevention reports that 68% of foodborne illness outbreaks originate from restaurants, yet restaurants remain a large part of our lives: a 2016 Gallup poll revealed that 61% of Americans eat at least one meal a week at a restaurants. Local governments are tasked with protecting the public from these illnesses. They achieve this by routinely investigating all restaurants, recording violations, correcting violations, and then publishing the results.

Our goal is to explore how people’s eating behaviors are influenced by health risks by revealing connections between food safety versus price, popularity, and location.

### Data Sources
To accomplish our stated goal, we obtained restaurant health records from King County’s Food Establishment Inspection dataset, [found here](https://data.kingcounty.gov/Health-Wellness/Food-Establishment-Inspection-Data/f29f-zza5). King County contains Seattle.

We then compared these food safety records with public perception data. We get these data from Zomato, an aggregator of restaurant review and user-generated information, which functions similarly to Yelp and Google Maps. [Link to data here](https://data.kingcounty.gov/Health-Wellness/Food-Establishment-Inspection-Data/f29f-zza5).
